//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Time
    {
        [Display(Name = "Id")]
        public int TimeID { get; set; }

        [Display(Name = "NomeTime")]
        [Required(ErrorMessage = "Informe o nome do time.")]
        public string Time1 { get; set; }

        [Required(ErrorMessage = "Informe o estado do time.")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "Informe as cores do time.")]
        public string Cores { get; set; }
    }
}
